// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ClassificationVersion : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Validity beginning date without time part.</summary>
        public Date? BeginDate { get; set; }
        /// <summary>Whether this is classifications default version</summary>
        public bool? DefaultVersion { get; set; }
        /// <summary>Validity expiration date without time part.</summary>
        public Date? ExpirationDate { get; set; }
        /// <summary>Date and time of last modification on this version</summary>
        public DateTimeOffset? LastModifiedDate { get; set; }
        /// <summary>HATEOAS link to full version details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.Link>? Links { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.Link> Links { get; set; }
#endif
        /// <summary>Whether remote Codeservers may use this classification version as a server load source</summary>
        public bool? ServerLoadSource { get; set; }
        /// <summary>Concept code status</summary>
        public global::ApiSdk.Models.Status? Status { get; private set; }
        /// <summary>Version identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionId { get; set; }
#nullable restore
#else
        public string VersionId { get; set; }
#endif
        /// <summary>Version name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionName { get; set; }
#nullable restore
#else
        public string VersionName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.ClassificationVersion"/> and sets the default values.
        /// </summary>
        public ClassificationVersion()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::ApiSdk.Models.Status.ACTIVE;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.ClassificationVersion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.ClassificationVersion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.ClassificationVersion();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "beginDate", n => { BeginDate = n.GetDateValue(); } },
                { "defaultVersion", n => { DefaultVersion = n.GetBoolValue(); } },
                { "expirationDate", n => { ExpirationDate = n.GetDateValue(); } },
                { "lastModifiedDate", n => { LastModifiedDate = n.GetDateTimeOffsetValue(); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::ApiSdk.Models.Link>(global::ApiSdk.Models.Link.CreateFromDiscriminatorValue)?.AsList(); } },
                { "serverLoadSource", n => { ServerLoadSource = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::ApiSdk.Models.Status>(); } },
                { "versionId", n => { VersionId = n.GetStringValue(); } },
                { "versionName", n => { VersionName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("beginDate", BeginDate);
            writer.WriteBoolValue("defaultVersion", DefaultVersion);
            writer.WriteDateValue("expirationDate", ExpirationDate);
            writer.WriteDateTimeOffsetValue("lastModifiedDate", LastModifiedDate);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.Link>("links", Links);
            writer.WriteBoolValue("serverLoadSource", ServerLoadSource);
            writer.WriteStringValue("versionId", VersionId);
            writer.WriteStringValue("versionName", VersionName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
