// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Classification type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Classification_classificationType
    {
        [EnumMember(Value = "CODES")]
        #pragma warning disable CS1591
        CODES,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORGANIZATIONS")]
        #pragma warning disable CS1591
        ORGANIZATIONS,
        #pragma warning restore CS1591
    }
}
