// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConceptCode : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Concept code attributes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.AttributeObject>? Attributes { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.AttributeObject> Attributes { get; set; }
#endif
        /// <summary>Validity beginning date without time part.</summary>
        public Date? BeginDate { get; set; }
        /// <summary>Classification identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClassificationId { get; private set; }
#nullable restore
#else
        public string ClassificationId { get; private set; }
#endif
        /// <summary>Classification name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClassificationName { get; private set; }
#nullable restore
#else
        public string ClassificationName { get; private set; }
#endif
        /// <summary>Concept code identifier. Cannot be updated after insert.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConceptCodeId { get; set; }
#nullable restore
#else
        public string ConceptCodeId { get; set; }
#endif
        /// <summary>Creation date and time.</summary>
        public DateTimeOffset? CreateDate { get; private set; }
        /// <summary>Validity expiration date without time part.</summary>
        public Date? ExpirationDate { get; set; }
        /// <summary>Name of last modifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastModifiedBy { get; private set; }
#nullable restore
#else
        public string LastModifiedBy { get; private set; }
#endif
        /// <summary>Last modified date and time.</summary>
        public DateTimeOffset? LastModifiedDate { get; private set; }
        /// <summary>Concept code status</summary>
        public global::ApiSdk.Models.Status? Status { get; private set; }
        /// <summary>Version identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionId { get; private set; }
#nullable restore
#else
        public string VersionId { get; private set; }
#endif
        /// <summary>Version name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionName { get; private set; }
#nullable restore
#else
        public string VersionName { get; private set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.ConceptCode"/> and sets the default values.
        /// </summary>
        public ConceptCode()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::ApiSdk.Models.Status.ACTIVE;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.ConceptCode"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.ConceptCode CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.ConceptCode();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetCollectionOfObjectValues<global::ApiSdk.Models.AttributeObject>(global::ApiSdk.Models.AttributeObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "beginDate", n => { BeginDate = n.GetDateValue(); } },
                { "classificationId", n => { ClassificationId = n.GetStringValue(); } },
                { "classificationName", n => { ClassificationName = n.GetStringValue(); } },
                { "conceptCodeId", n => { ConceptCodeId = n.GetStringValue(); } },
                { "createDate", n => { CreateDate = n.GetDateTimeOffsetValue(); } },
                { "expirationDate", n => { ExpirationDate = n.GetDateValue(); } },
                { "lastModifiedBy", n => { LastModifiedBy = n.GetStringValue(); } },
                { "lastModifiedDate", n => { LastModifiedDate = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::ApiSdk.Models.Status>(); } },
                { "versionId", n => { VersionId = n.GetStringValue(); } },
                { "versionName", n => { VersionName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.AttributeObject>("attributes", Attributes);
            writer.WriteDateValue("beginDate", BeginDate);
            writer.WriteStringValue("conceptCodeId", ConceptCodeId);
            writer.WriteDateValue("expirationDate", ExpirationDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
