// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConceptCodes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Array of concept codes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.ConceptCode>? ConceptCodesProp { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.ConceptCode> ConceptCodesProp { get; set; }
#endif
        /// <summary>Current page number</summary>
        public int? Page { get; private set; }
        /// <summary>Maximum number of concept codes in one page. If the value is same as the value of totalPages then further pages are not available.</summary>
        public int? PageSize { get; private set; }
        /// <summary>Total number of concept codes.</summary>
        public int? TotalItems { get; private set; }
        /// <summary>Total number of pages.</summary>
        public int? TotalPages { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.ConceptCodes"/> and sets the default values.
        /// </summary>
        public ConceptCodes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.ConceptCodes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.ConceptCodes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.ConceptCodes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "conceptCodes", n => { ConceptCodesProp = n.GetCollectionOfObjectValues<global::ApiSdk.Models.ConceptCode>(global::ApiSdk.Models.ConceptCode.CreateFromDiscriminatorValue)?.AsList(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "totalItems", n => { TotalItems = n.GetIntValue(); } },
                { "totalPages", n => { TotalPages = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.ConceptCode>("conceptCodes", ConceptCodesProp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
