// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Sub-type of attribute field. Used when fieldType is ATTRIBUTE.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Field_fieldSubType
    {
        [EnumMember(Value = "NUMERIC")]
        #pragma warning disable CS1591
        NUMERIC,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHORTTEXT")]
        #pragma warning disable CS1591
        SHORTTEXT,
        #pragma warning restore CS1591
        [EnumMember(Value = "LONGTEXT")]
        #pragma warning disable CS1591
        LONGTEXT,
        #pragma warning restore CS1591
        [EnumMember(Value = "FORMATTEDTEXT")]
        #pragma warning disable CS1591
        FORMATTEDTEXT,
        #pragma warning restore CS1591
        [EnumMember(Value = "VALUESET")]
        #pragma warning disable CS1591
        VALUESET,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE")]
        #pragma warning disable CS1591
        DATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "LINK")]
        #pragma warning disable CS1591
        LINK,
        #pragma warning restore CS1591
    }
}
