// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Type of the field</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Field_fieldType
    {
        [EnumMember(Value = "BASE")]
        #pragma warning disable CS1591
        BASE,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIXED")]
        #pragma warning disable CS1591
        FIXED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ATTRIBUTE")]
        #pragma warning disable CS1591
        ATTRIBUTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "REFERENCE")]
        #pragma warning disable CS1591
        REFERENCE,
        #pragma warning restore CS1591
    }
}
