// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Fixed price field name(s) to be used as search criteria targets</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PriceQfield
    {
        [EnumMember(Value = "PRICEID")]
        #pragma warning disable CS1591
        PRICEID,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCTID")]
        #pragma warning disable CS1591
        PRODUCTID,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCERID")]
        #pragma warning disable CS1591
        PRODUCERID,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOMERID")]
        #pragma warning disable CS1591
        CUSTOMERID,
        #pragma warning restore CS1591
    }
}
