// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>A field name by which prices should be sorted in ascending order</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PriceSortBy
    {
        [EnumMember(Value = "PRICEID")]
        #pragma warning disable CS1591
        PRICEID,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCTID")]
        #pragma warning disable CS1591
        PRODUCTID,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCERID")]
        #pragma warning disable CS1591
        PRODUCERID,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOMERID")]
        #pragma warning disable CS1591
        CUSTOMERID,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRICE1")]
        #pragma warning disable CS1591
        PRICE1,
        #pragma warning restore CS1591
        [EnumMember(Value = "BEGINDATE")]
        #pragma warning disable CS1591
        BEGINDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRATIONDATE")]
        #pragma warning disable CS1591
        EXPIRATIONDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "LASTMODIFIEDBY")]
        #pragma warning disable CS1591
        LASTMODIFIEDBY,
        #pragma warning restore CS1591
        [EnumMember(Value = "LASTMODIFIEDDATE")]
        #pragma warning disable CS1591
        LASTMODIFIEDDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREATEDATE")]
        #pragma warning disable CS1591
        CREATEDATE,
        #pragma warning restore CS1591
    }
}
