// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    /// <summary>
    /// CodeServer price list metadata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PriceList : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Customer classification id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerClassificationId { get; set; }
#nullable restore
#else
        public string CustomerClassificationId { get; set; }
#endif
        /// <summary>Customer classification name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerClassificationName { get; set; }
#nullable restore
#else
        public string CustomerClassificationName { get; set; }
#endif
        /// <summary>Customers friendly name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomersName { get; set; }
#nullable restore
#else
        public string CustomersName { get; set; }
#endif
        /// <summary>Customer version id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerVersionId { get; set; }
#nullable restore
#else
        public string CustomerVersionId { get; set; }
#endif
        /// <summary>Customer version name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerVersionName { get; set; }
#nullable restore
#else
        public string CustomerVersionName { get; set; }
#endif
        /// <summary>Fields of price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.Field>? Definitions { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.Field> Definitions { get; set; }
#endif
        /// <summary>Price list friendly name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PricelistName { get; set; }
#nullable restore
#else
        public string PricelistName { get; set; }
#endif
        /// <summary>Producer classification id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProducerClassificationId { get; set; }
#nullable restore
#else
        public string ProducerClassificationId { get; set; }
#endif
        /// <summary>Producer classification name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProducerClassificationName { get; set; }
#nullable restore
#else
        public string ProducerClassificationName { get; set; }
#endif
        /// <summary>Producers friendly name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProducersName { get; set; }
#nullable restore
#else
        public string ProducersName { get; set; }
#endif
        /// <summary>Producer version id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProducerVersionId { get; set; }
#nullable restore
#else
        public string ProducerVersionId { get; set; }
#endif
        /// <summary>Producer version name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProducerVersionName { get; set; }
#nullable restore
#else
        public string ProducerVersionName { get; set; }
#endif
        /// <summary>Product classification id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductClassificationId { get; set; }
#nullable restore
#else
        public string ProductClassificationId { get; set; }
#endif
        /// <summary>Product classification name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductClassificationName { get; set; }
#nullable restore
#else
        public string ProductClassificationName { get; set; }
#endif
        /// <summary>Product version id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductVersionId { get; set; }
#nullable restore
#else
        public string ProductVersionId { get; set; }
#endif
        /// <summary>Product version name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductVersionName { get; set; }
#nullable restore
#else
        public string ProductVersionName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.PriceList"/> and sets the default values.
        /// </summary>
        public PriceList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.PriceList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.PriceList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.PriceList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customerClassificationId", n => { CustomerClassificationId = n.GetStringValue(); } },
                { "customerClassificationName", n => { CustomerClassificationName = n.GetStringValue(); } },
                { "customerVersionId", n => { CustomerVersionId = n.GetStringValue(); } },
                { "customerVersionName", n => { CustomerVersionName = n.GetStringValue(); } },
                { "customersName", n => { CustomersName = n.GetStringValue(); } },
                { "definitions", n => { Definitions = n.GetCollectionOfObjectValues<global::ApiSdk.Models.Field>(global::ApiSdk.Models.Field.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pricelistName", n => { PricelistName = n.GetStringValue(); } },
                { "producerClassificationId", n => { ProducerClassificationId = n.GetStringValue(); } },
                { "producerClassificationName", n => { ProducerClassificationName = n.GetStringValue(); } },
                { "producerVersionId", n => { ProducerVersionId = n.GetStringValue(); } },
                { "producerVersionName", n => { ProducerVersionName = n.GetStringValue(); } },
                { "producersName", n => { ProducersName = n.GetStringValue(); } },
                { "productClassificationId", n => { ProductClassificationId = n.GetStringValue(); } },
                { "productClassificationName", n => { ProductClassificationName = n.GetStringValue(); } },
                { "productVersionId", n => { ProductVersionId = n.GetStringValue(); } },
                { "productVersionName", n => { ProductVersionName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("customerClassificationId", CustomerClassificationId);
            writer.WriteStringValue("customerClassificationName", CustomerClassificationName);
            writer.WriteStringValue("customersName", CustomersName);
            writer.WriteStringValue("customerVersionId", CustomerVersionId);
            writer.WriteStringValue("customerVersionName", CustomerVersionName);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.Field>("definitions", Definitions);
            writer.WriteStringValue("pricelistName", PricelistName);
            writer.WriteStringValue("producerClassificationId", ProducerClassificationId);
            writer.WriteStringValue("producerClassificationName", ProducerClassificationName);
            writer.WriteStringValue("producersName", ProducersName);
            writer.WriteStringValue("producerVersionId", ProducerVersionId);
            writer.WriteStringValue("producerVersionName", ProducerVersionName);
            writer.WriteStringValue("productClassificationId", ProductClassificationId);
            writer.WriteStringValue("productClassificationName", ProductClassificationName);
            writer.WriteStringValue("productVersionId", ProductVersionId);
            writer.WriteStringValue("productVersionName", ProductVersionName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
