// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Price : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Price attributes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.AttributeObject>? Attributes { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.AttributeObject> Attributes { get; set; }
#endif
        /// <summary>Validity beginning date without time part.</summary>
        public Date? BeginDate { get; set; }
        /// <summary>Creation date and time.</summary>
        public DateTimeOffset? CreateDate { get; set; }
        /// <summary>Validity expiration date without time part.</summary>
        public Date? ExpirationDate { get; set; }
        /// <summary>Name of last modifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastModifiedBy { get; set; }
#nullable restore
#else
        public string LastModifiedBy { get; set; }
#endif
        /// <summary>Last modified date and time.</summary>
        public DateTimeOffset? LastModifiedDate { get; set; }
        /// <summary>Price of product</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Price1 { get; set; }
#nullable restore
#else
        public string Price1 { get; set; }
#endif
        /// <summary>Price identifier = OID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PriceId { get; set; }
#nullable restore
#else
        public string PriceId { get; set; }
#endif
        /// <summary>Price list name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PricelistName { get; set; }
#nullable restore
#else
        public string PricelistName { get; set; }
#endif
        /// <summary>Price status</summary>
        public global::ApiSdk.Models.PriceStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.Price"/> and sets the default values.
        /// </summary>
        public Price()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::ApiSdk.Models.PriceStatus.ACTIVE;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.Price"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.Price CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.Price();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetCollectionOfObjectValues<global::ApiSdk.Models.AttributeObject>(global::ApiSdk.Models.AttributeObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "beginDate", n => { BeginDate = n.GetDateValue(); } },
                { "createDate", n => { CreateDate = n.GetDateTimeOffsetValue(); } },
                { "expirationDate", n => { ExpirationDate = n.GetDateValue(); } },
                { "lastModifiedBy", n => { LastModifiedBy = n.GetStringValue(); } },
                { "lastModifiedDate", n => { LastModifiedDate = n.GetDateTimeOffsetValue(); } },
                { "price1", n => { Price1 = n.GetStringValue(); } },
                { "priceId", n => { PriceId = n.GetStringValue(); } },
                { "pricelistName", n => { PricelistName = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::ApiSdk.Models.PriceStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.AttributeObject>("attributes", Attributes);
            writer.WriteDateValue("beginDate", BeginDate);
            writer.WriteDateTimeOffsetValue("createDate", CreateDate);
            writer.WriteDateValue("expirationDate", ExpirationDate);
            writer.WriteStringValue("lastModifiedBy", LastModifiedBy);
            writer.WriteDateTimeOffsetValue("lastModifiedDate", LastModifiedDate);
            writer.WriteStringValue("price1", Price1);
            writer.WriteStringValue("priceId", PriceId);
            writer.WriteStringValue("pricelistName", PricelistName);
            writer.WriteEnumValue<global::ApiSdk.Models.PriceStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
