// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Fixed field name(s) to be used as search criteria targets</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Qfield
    {
        [EnumMember(Value = "CONCEPTCODEID")]
        #pragma warning disable CS1591
        CONCEPTCODEID,
        #pragma warning restore CS1591
        [EnumMember(Value = "ABBREVIATION")]
        #pragma warning disable CS1591
        ABBREVIATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "NAME")]
        #pragma warning disable CS1591
        NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARENTID")]
        #pragma warning disable CS1591
        PARENTID,
        #pragma warning restore CS1591
    }
}
