// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>A field name by which concept codes should be sorted in ascending order</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SortBy
    {
        [EnumMember(Value = "CONCEPTCODEID")]
        #pragma warning disable CS1591
        CONCEPTCODEID,
        #pragma warning restore CS1591
        [EnumMember(Value = "ABBREVIATION")]
        #pragma warning disable CS1591
        ABBREVIATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "NAME")]
        #pragma warning disable CS1591
        NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARENTID")]
        #pragma warning disable CS1591
        PARENTID,
        #pragma warning restore CS1591
        [EnumMember(Value = "BEGINDATE")]
        #pragma warning disable CS1591
        BEGINDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRATIONDATE")]
        #pragma warning disable CS1591
        EXPIRATIONDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "OID")]
        #pragma warning disable CS1591
        OID,
        #pragma warning restore CS1591
        [EnumMember(Value = "LASTMODIFIEDBY")]
        #pragma warning disable CS1591
        LASTMODIFIEDBY,
        #pragma warning restore CS1591
        [EnumMember(Value = "LASTMODIFIEDDATE")]
        #pragma warning disable CS1591
        LASTMODIFIEDDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREATEDATE")]
        #pragma warning disable CS1591
        CREATEDATE,
        #pragma warning restore CS1591
    }
}
