// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Type of hierarchy validation. Only relevant for versions in hierarchical classifications.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Version_hierarchyIntegrity
    {
        [EnumMember(Value = "STRICT")]
        #pragma warning disable CS1591
        STRICT,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOOSE")]
        #pragma warning disable CS1591
        LOOSE,
        #pragma warning restore CS1591
    }
}
