// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.V6.Classifications.Item.Pricelists.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
namespace ApiSdk.V6.Classifications.Item.Pricelists
{
    /// <summary>
    /// Builds and executes requests for operations under \v6\classifications\{classificationId}\pricelists
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PricelistsRequestBuilder : BaseCliRequestBuilder
    {
        /// <summary>
        /// Gets an item from the ApiSdk.v6.classifications.item.pricelists.item collection
        /// </summary>
        /// <returns>A Tuple&lt;List&lt;Command&gt;, List&lt;Command&gt;&gt;</returns>
        public Tuple<List<Command>, List<Command>> BuildCommand()
        {
            var executables = new List<Command>();
            var commands = new List<Command>();
            var builder = new global::ApiSdk.V6.Classifications.Item.Pricelists.Item.WithPricelistItemRequestBuilder(PathParameters);
            executables.Add(builder.BuildGetCommand());
            commands.Add(builder.BuildPricesNavCommand());
            return new(executables, commands);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V6.Classifications.Item.Pricelists.PricelistsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        public PricelistsRequestBuilder(Dictionary<string, object> pathParameters) : base("{+baseurl}/v6/classifications/{classificationId}/pricelists", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V6.Classifications.Item.Pricelists.PricelistsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public PricelistsRequestBuilder(string rawUrl) : base("{+baseurl}/v6/classifications/{classificationId}/pricelists", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
