// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Auth;
using ApiSdk.V6;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
namespace ApiSdk
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseCliRequestBuilder
    {
        /// <summary>
        /// The auth property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildAuthNavCommand()
        {
            var command = new Command("auth");
            command.Description = "The auth property";
            var builder = new global::ApiSdk.Auth.AuthRequestBuilder(PathParameters);
            var nonExecCommands = new List<Command>();
            nonExecCommands.Add(builder.BuildApiLoginNavCommand());
            nonExecCommands.Add(builder.BuildApiLogoutNavCommand());
            foreach (var cmd in nonExecCommands)
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.ApiClient"/> and sets the default values.
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildRootCommand()
        {
            var command = new RootCommand();
            command.Description = "Instantiates a new ApiClient and sets the default values.";
            command.AddCommand(BuildAuthNavCommand());
            command.AddCommand(BuildV6NavCommand());
            return command;
        }
        /// <summary>
        /// The v6 property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildV6NavCommand()
        {
            var command = new Command("v6");
            command.Description = "The v6 property";
            var builder = new global::ApiSdk.V6.V6RequestBuilder(PathParameters);
            var nonExecCommands = new List<Command>();
            nonExecCommands.Add(builder.BuildClassificationsNavCommand());
            foreach (var cmd in nonExecCommands)
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.ApiClient"/> and sets the default values.
        /// </summary>
        public ApiClient() : base("{+baseurl}", new Dictionary<string, object>())
        {
        }
    }
}
#pragma warning restore CS0618
