// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Auth.ApiLogin;
using ApiSdk.Auth.ApiLogout;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseCliRequestBuilder
    {
        /// <summary>
        /// The apiLogin property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildApiLoginNavCommand()
        {
            var command = new Command("api-login");
            command.Description = "The apiLogin property";
            var builder = new global::ApiSdk.Auth.ApiLogin.ApiLoginRequestBuilder(PathParameters);
            var execCommands = new List<Command>();
            execCommands.Add(builder.BuildPostCommand());
            foreach (var cmd in execCommands)
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// The apiLogout property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildApiLogoutNavCommand()
        {
            var command = new Command("api-logout");
            command.Description = "The apiLogout property";
            var builder = new global::ApiSdk.Auth.ApiLogout.ApiLogoutRequestBuilder(PathParameters);
            var execCommands = new List<Command>();
            execCommands.Add(builder.BuildPostCommand());
            foreach (var cmd in execCommands)
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters) : base("{+baseurl}/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public AuthRequestBuilder(string rawUrl) : base("{+baseurl}/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
