// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models;
using ApiSdk.V6.Classifications.Item.Pricelists.Item.Prices;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.Extensions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.V6.Classifications.Item.Pricelists.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v6\classifications\{classificationId}\pricelists\{pricelistId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPricelistItemRequestBuilder : BaseCliRequestBuilder
    {
        /// <summary>
        /// Get description (metadata) of specified price list resource.
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildGetCommand()
        {
            var command = new Command("get");
            command.Description = "Get description (metadata) of specified price list resource.";
            var classificationIdOption = new Option<string>("--classification-id", description: "Classification identifier") {
            };
            classificationIdOption.IsRequired = true;
            command.AddOption(classificationIdOption);
            var pricelistIdOption = new Option<string>("--pricelist-id", description: "Price list identifier, same as version identifier of the price list product classification version.") {
            };
            pricelistIdOption.IsRequired = true;
            command.AddOption(pricelistIdOption);
            var outputOption = new Option<FormatterType>("--output", () => FormatterType.JSON);
            command.AddOption(outputOption);
            var queryOption = new Option<string>("--query");
            command.AddOption(queryOption);
            command.SetHandler(async (invocationContext) => {
                var classificationId = invocationContext.ParseResult.GetValueForOption(classificationIdOption);
                var pricelistId = invocationContext.ParseResult.GetValueForOption(pricelistIdOption);
                var output = invocationContext.ParseResult.GetValueForOption(outputOption);
                var query = invocationContext.ParseResult.GetValueForOption(queryOption);
                IOutputFilter outputFilter = invocationContext.BindingContext.GetService(typeof(IOutputFilter)) as IOutputFilter ?? throw new ArgumentNullException("outputFilter");
                IOutputFormatterFactory outputFormatterFactory = invocationContext.BindingContext.GetService(typeof(IOutputFormatterFactory)) as IOutputFormatterFactory ?? throw new ArgumentNullException("outputFormatterFactory");
                var cancellationToken = invocationContext.GetCancellationToken();
                var reqAdapter = invocationContext.GetRequestAdapter();
                var requestInfo = ToGetRequestInformation(q => {
                });
                if (classificationId is not null) requestInfo.PathParameters.Add("classificationId", classificationId);
                if (pricelistId is not null) requestInfo.PathParameters.Add("pricelistId", pricelistId);
                var errorMapping = new Dictionary<string, ParsableFactory<IParsable>> {
                    {"401", Error.CreateFromDiscriminatorValue},
                    {"403", Error.CreateFromDiscriminatorValue},
                    {"404", Error.CreateFromDiscriminatorValue},
                    {"500", Error.CreateFromDiscriminatorValue},
                };
                var response = await reqAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping: errorMapping, cancellationToken: cancellationToken) ?? Stream.Null;
                response = (response != Stream.Null) ? await outputFilter.FilterOutputAsync(response, query, cancellationToken) : response;
                var formatter = outputFormatterFactory.GetFormatter(output);
                await formatter.WriteOutputAsync(response, cancellationToken);
            });
            return command;
        }
        /// <summary>
        /// The prices property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildPricesNavCommand()
        {
            var command = new Command("prices");
            command.Description = "The prices property";
            var builder = new global::ApiSdk.V6.Classifications.Item.Pricelists.Item.Prices.PricesRequestBuilder(PathParameters);
            var execCommands = new List<Command>();
            var nonExecCommands = new List<Command>();
            execCommands.Add(builder.BuildListCommand());
            var cmds = builder.BuildCommand();
            execCommands.AddRange(cmds.Item1);
            nonExecCommands.AddRange(cmds.Item2);
            foreach (var cmd in execCommands)
            {
                command.AddCommand(cmd);
            }
            foreach (var cmd in nonExecCommands.OrderBy(static c => c.Name, StringComparer.Ordinal))
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V6.Classifications.Item.Pricelists.Item.WithPricelistItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        public WithPricelistItemRequestBuilder(Dictionary<string, object> pathParameters) : base("{+baseurl}/v6/classifications/{classificationId}/pricelists/{pricelistId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V6.Classifications.Item.Pricelists.Item.WithPricelistItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public WithPricelistItemRequestBuilder(string rawUrl) : base("{+baseurl}/v6/classifications/{classificationId}/pricelists/{pricelistId}", rawUrl)
        {
        }
        /// <summary>
        /// Get description (metadata) of specified price list resource.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
    }
}
#pragma warning restore CS0618
