// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.V6.Classifications.Item.Conceptcodes;
using ApiSdk.V6.Classifications.Item.Pricelists;
using ApiSdk.V6.Classifications.Item.Versions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
namespace ApiSdk.V6.Classifications.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v6\classifications\{classificationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithClassificationItemRequestBuilder : BaseCliRequestBuilder
    {
        /// <summary>
        /// The conceptcodes property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildConceptcodesNavCommand()
        {
            var command = new Command("conceptcodes");
            command.Description = "The conceptcodes property";
            var builder = new global::ApiSdk.V6.Classifications.Item.Conceptcodes.ConceptcodesRequestBuilder(PathParameters);
            var execCommands = new List<Command>();
            var nonExecCommands = new List<Command>();
            execCommands.Add(builder.BuildCreateCommand());
            execCommands.Add(builder.BuildListCommand());
            var cmds = builder.BuildCommand();
            execCommands.AddRange(cmds.Item1);
            nonExecCommands.AddRange(cmds.Item2);
            foreach (var cmd in execCommands)
            {
                command.AddCommand(cmd);
            }
            foreach (var cmd in nonExecCommands.OrderBy(static c => c.Name, StringComparer.Ordinal))
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// The pricelists property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildPricelistsNavCommand()
        {
            var command = new Command("pricelists");
            command.Description = "The pricelists property";
            var builder = new global::ApiSdk.V6.Classifications.Item.Pricelists.PricelistsRequestBuilder(PathParameters);
            var nonExecCommands = new List<Command>();
            var cmds = builder.BuildCommand();
            nonExecCommands.AddRange(cmds.Item2);
            foreach (var cmd in nonExecCommands.OrderBy(static c => c.Name, StringComparer.Ordinal))
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// The versions property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildVersionsNavCommand()
        {
            var command = new Command("versions");
            command.Description = "The versions property";
            var builder = new global::ApiSdk.V6.Classifications.Item.Versions.VersionsRequestBuilder(PathParameters);
            var execCommands = new List<Command>();
            var nonExecCommands = new List<Command>();
            execCommands.Add(builder.BuildListCommand());
            var cmds = builder.BuildCommand();
            execCommands.AddRange(cmds.Item1);
            nonExecCommands.AddRange(cmds.Item2);
            foreach (var cmd in execCommands)
            {
                command.AddCommand(cmd);
            }
            foreach (var cmd in nonExecCommands.OrderBy(static c => c.Name, StringComparer.Ordinal))
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V6.Classifications.Item.WithClassificationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        public WithClassificationItemRequestBuilder(Dictionary<string, object> pathParameters) : base("{+baseurl}/v6/classifications/{classificationId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V6.Classifications.Item.WithClassificationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public WithClassificationItemRequestBuilder(string rawUrl) : base("{+baseurl}/v6/classifications/{classificationId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
